## Часть 1

In [1]:
import torch
import numpy as np

### 1.)

In [2]:
tensor = torch.rand(3,2)
tensor

tensor([[0.7497, 0.5044],
        [0.6373, 0.4094],
        [0.8145, 0.6261]])

### 2.)

In [3]:
tensor1 = torch.ones(2, 3)
torch.matmul(tensor,tensor1)

tensor([[1.2542, 1.2542, 1.2542],
        [1.0467, 1.0467, 1.0467],
        [1.4406, 1.4406, 1.4406]])

### 3.)

In [4]:
rand_tensor1 = torch.rand(3,2)
rand_tensor2 = torch.rand(3,2)
sum_tensor = rand_tensor1 + rand_tensor2
sum_tensor

tensor([[1.0405, 0.2553],
        [0.4890, 1.2691],
        [1.4223, 1.4866]])

### 4.)

In [5]:
print('First row: ', tensor[0])

First row:  tensor([0.7497, 0.5044])


### 5.)

In [6]:
print('First column: ', tensor[:, 0])

First column:  tensor([0.7497, 0.6373, 0.8145])


### 6.)

In [7]:
new_tensor1 = torch.rand(5,)
new_tensor2 = torch.rand(5,)
unite_tensor_row = torch.cat([new_tensor1, new_tensor2])
print('Tensor row: ', unite_tensor_row.shape)
unite_tensor_table = torch.stack([new_tensor1, new_tensor2])
print('Tensor table: ', unite_tensor_table.shape)

Tensor row:  torch.Size([10])
Tensor table:  torch.Size([2, 5])


### 7.)

In [8]:
print('Shape: ', tensor.shape)

Shape:  torch.Size([3, 2])


## Часть 2

In [9]:
x = torch.tensor(1.0, requires_grad = True) #первый параметр означает, что будет создан тензор, состоящий из единицы.
#второй параметр имеет значение true, поэтому будет отслеживаться история операций и формироваться граф для вычисления градиента.

In [10]:
z = x ** 4 #создается тензор, который хранит значение тензора x в 4 степени
z.backward() #вычисляется градиент тензора
print(x.grad.data) #выведется тензор, содержащий цифру 4. Получили из 4*x^3

tensor(4.)
